services:
  grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "8080:3000"
      environment:
        - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
      volumes:
        - grafana-storage:/var/lib/grafana
        - ./grafana/provisioning:/etc/grafana/provisioning
      restart: unless-stopped

  redis: 
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - monitoring
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.10'
          memory: 128M
  api:
    container_name: api
    build:
      context: . 
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - grafana
      - redis
    networks:
      - monitoring
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
          
volumes:
  grafana-storage:
    driver: local

networks:
  monitoring:
    driver: bridge